### PR TITLE
Guild emoji develop

### LINKED ISSUE #35: Add guild emoji functions
It would be a nice improvement to add the emoji actions on the guild that are described in the discord API (https://discordapp.com/developers/docs/resources/emoji#list-guild-emojis).

### PR DESCRIPTION
**Pull request by janvernieuwe**
Fixes #35 
Based on develop branch, cherry picked the changes

### CODE REVIEW

**Comment by aequasi** [comment]
This SHOULD get fixed as soon as https://github.com/discordapp/discord-api-docs/pull/501 is merged and pushed live

**Comment by aequasi** [comment]
Can you check dev-develop and see if it has everything you need?

**Comment by janvernieuwe** [comment]
I think there is a bug in the namespace of the RateLimitProviders.
image

image

The namespace does not match the directory structure and fails to load the provider.

**Comment by aequasi** [comment]
Yup! Fixed. Sorry about that.

**Comment by aequasi** [comment]
The methods you wanted to add got added to their own resource, under emoji: `$client->emoji->listGuildEmojis()`

**Comment by janvernieuwe** [comment]
Ok, I'll try it out tonight.
Thanks for the updates!

**Pull request closed without merging**
