### PR TITLE
Added User Banner Support

### PR DESCRIPTION
**Pull request by Sawaya-ui**
I'vent been working on restcord for a long time and saw that there is no user banner support yet, so I wanted to catch up quickly.

### CODE REVIEW

**Comment by cryptiklemur** [comment]
Please fix the conflicts and style issues

**Comment by Sawaya-ui** [comment]
@aequasi ?

**Comment by cryptiklemur** [comment]
You didnt fix the conflicts or style issues

**Comment by Sawaya-ui** [comment]
what? in which file is that?

**Comment by cryptiklemur** [comment]
Please view the issues that are listed at the bottom of this page

**Comment by Sawaya-ui** [comment]
> Please view the issues that are listed at the bottom of this page

Yes the Constants.php. I added the things that is missing

**Comment by Sawaya-ui** [comment]
The changes in the Constants file include a Discord CDN link which I added to make the whole thing work.

**Comment by cryptiklemur** [comment]
I cannot merge this until you fix the issues that are listed at the bottom of the page. Feel free to ping again once they are fixed

**Comment by kirihito-kun** [comment]
@aequasi So I reverted my changes and yea idk what I should do now. I hope it works now, otherwise I won't get any further and won't change anything because I think that no matter what I change, there will always be a problem.

**Pull request closed without merging**
