### PR TITLE
Update for Guzzle 7

### PR DESCRIPTION
**Pull request by bumbummen99**

### CODE REVIEW

**Comment by bumbummen99** [comment]
@aequasi I have no clue what exactly is going on with the Style CI on this repository, maybe we should try to re-activate / reset it? It seems like it's configuration got stuck.

**Comment by bumbummen99** [comment]
Any chance on getting this merged?

**Comment by alexstojda** [comment]
Bump! I need this update as well!

**Comment by csnuknet** [comment]
+ 1 would be great to get Guzzle 7 support

**Comment by dmyers** [comment]
Wouldn't it be better to still allow projects to use Guzzle 6 if they want to? This kind of makes upgrading more difficult not easier in many cases this would benefit all: `"guzzlehttp/guzzle": "^6.3|^7.0"`.

**Comment by bumbummen99** [comment]
> Wouldn't it be better to still allow projects to use Guzzle 6 if they want to? This kind of makes upgrading more difficult not easier in many cases this would benefit all: `"guzzlehttp/guzzle": "^6.3|^7.0"`. For the message formatter, maybe the typehint for either `exception` or `throwable` could be just simply removed.

The "problem" was that the [MessageFormatter](https://github.com/guzzle/guzzle/blob/2d9d3c186a6637a43193e66b097c50e4451eaab2/src/MessageFormatter.php#L69) requires it to be `\Throwable` and $response to be nullable, it is no interface thought. We can pass the parameters through and the original formatter that is being called should handle the type checking thought i am not a big fan of doing such trickery, i'd rather have it explicit and update the consuming code. That said, can you check if the latest changes work for you?

**Comment by agentom** [comment]
Hi guys ! great work, 
I'm currently stuck with my app, I'm using your library for sync my Symfony 5 website with discord and I need to implement DiscordPHP-Slash... who needs guzzle ^7.2 ... so, are you planning to merge soon ? It would be a big help !

**Comment by oliverschloebe** [comment]
> Hi guys ! great work,
> I'm currently stuck with my app, I'm using your library for sync my Symfony 5 website with discord and I need to implement DiscordPHP-Slash... who needs guzzle ^7.2 ... so, are you planning to merge soon ? It would be a big help !

In Discord I was suggested to add the following to the `composer.json` for the time being:

```
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/bumbummen99/restcord"
    }
  ],
  "require": {
    "restcord/restcord": "dev-patch-2"
  }
}
```

Havn't tested myself yet though.

**Comment by bumbummen99** [comment]
> > Hi guys ! great work,
> > I'm currently stuck with my app, I'm using your library for sync my Symfony 5 website with discord and I need to implement DiscordPHP-Slash... who needs guzzle ^7.2 ... so, are you planning to merge soon ? It would be a big help !
> 
> In Discord I was suggested to add the following to the `composer.json` for the time being:
> 
> ```
> {
>   "repositories": [
>     {
>       "type": "vcs",
>       "url": "https://github.com/bumbummen99/restcord"
>     }
>   ],
>   "require": {
>     "restcord/restcord": "dev-patch-2"
>   }
> }
> ```
> 
> Havn't tested myself yet though.

Should be fine to use as i have been using it in production for months now :+1: You should not forget to keep an eye on this PR and remove it when it is merged as i wont maintain it.

**Pull request merged**
