### PR TITLE
Discord API V9

### PR DESCRIPTION
**Pull request by BriqueAuBob**
Hi.

Here is the generated code/docs to change the current api version used by RestCord (v6) to use the latest version of the API (v9) that implement threads for example...

### CODE REVIEW

**Comment by cryptiklemur** [comment]
Have you tested this? Did you need to make changes to the generator code?

**Comment by BriqueAuBob** [comment]
I have run the tests in `tests` dir and tested the thread creation (which is a new feature of V9 but i didn't have tested anything else)

The only thing i needed to change was the service_description JSON file that is available here: 
https://discord-service-definition.herokuapp.com/ 
because some params was with "?" and/or "*" in their name so, due to that params was not sent in the correct way.
I don't know if this file provided by https://discord-service-definition.herokuapp.com/ is up to date (with latest v9 features so it may have some missing features, I will check it later)

**Comment by BriqueAuBob** [comment]
That was not up to date but now that's good!

**Comment by cryptiklemur** [comment]
This is available in `dev-v9` now. Please test it out, and if it works well, I'll merge it into develop for more testing

**Pull request merged**
