### PR TITLE
Change joined_at to string

### PR DESCRIPTION
**Pull request by f0nt4**
Changing this variable to a string gives back the complete date, in stead of just the year.

### CODE REVIEW

**Comment by f0nt4** [comment]
For example my user now gives back `joined_at: "2015"`
while after changing it to string it gives back `joined_at: "2015-12-15T10:38:40.383000+00:00"`

**Comment by f0nt4** [comment]
Even better would be to change it to a datetime.

**Comment by f0nt4** [comment]
Now after changing it to "ISO8601 timestamp" / "\DateTimeImmutable" you can use it in php as a datetime object which makes it possible to do things like:
`$guild->user->joined_at->format('d-m-Y H:i:s')`
which results in:
`15-12-2015 10:38:40`

**Comment by f0nt4** [comment]
I've completely updated the service description json.
Walked through the whole file on 1 monitor and the docs on another one. Fixed all faults that I could find.
Should all be correct now.
Maybe you can regenerate the function files?

**Comment by aequasi** [comment]
The service definition is automatically generated as well, this file will get overridden when everything gets generated

**Comment by f0nt4** [comment]
How's the file automatically generated? When has that been done for the last time? The change to the new docs has already been a while, and in the meantime numerous change have been made.

**Comment by f0nt4** [comment]
Was able to get the service definition generator to work.
This is a fresh updated version of the file.
I've removed `"default": false,` from mute and deaf in the modify guild member section.

**Comment by f0nt4** [comment]
I'm closing this PR as we now have an updated version of Restcord in the develop branch.

**Pull request closed without merging**
